### ISSUE TITLE
Frontend / Register Form refine 진행상황

### ISSUE THREAD

**Issue by hajun-myoung** [ParkSuJeong74/21cDevelopers#7]
# Purpose

이 이슈는 Frontend 에서 Register Form의 진행상황을 체크하고, 공유하기 위해 오픈했습니다

## Todo

- [x] mui 적용하여 기본적인 틀 잡기
  - Figma 참고
    <img width="452" alt="스크린샷 2022-04-08 오전 1 45 59" src="https://user-images.githubusercontent.com/14975319/162255094-22da74a7-68d4-468a-94ec-814bfa43e044.png">
- [ ] `/register/` 경로에서 Header, Nav 가 보이지 않도록 만들기
- [ ] `/register/` 경로의 배경을 연한 회색(#FFF)로 채우기
  - 상위 `App.js`에서 전체를 감싸는 Wrapper를 새로 만들어줘야 할 것 같음
- [ ] 이메일 인증 (isCheckedEmail)의 로직 변경하기
  - 기존 : Modal 창을 띄워서 처리
  - 목표 : `/register/` 페이지 안에서 인증번호 입력과 인증이 가능하게끔
- [ ] 모든 기능이 이전과 같이 동작하는지 확인하기

### optional
- [ ] 배경의 연한 회색 처리 후, register card에 glassmorphism 적용해보기

## Close

이 이슈에 할당된 Todo가 모두 완료되면 @hajun-myoung 이 클로즈 할 예정입니다
